services:
  test-db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_DB=powerlogger_test
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5433:5432"
    volumes:
      - test_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 5s
      retries: 10
    restart: unless-stopped

  test-runner:
    build: .
    environment:
      - DATABASE_URL=postgres://postgres:postgres@test-db:5432/powerlogger_test?sslmode=disable
      - GIN_MODE=test
    depends_on:
      test-db:
        condition: service_healthy
    command: ["go", "test", "-v", "./..."]
    volumes:
      - .:/app
    working_dir: /app

volumes:
  test_postgres_data: