version: '3.8'

# Development override for docker-compose.yml
# Usage: docker-compose -f docker-compose.yml -f docker-compose.dev.yml up

services:
  postgres:
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: power_logger_dev
      POSTGRES_USER: power_logger_dev
      POSTGRES_PASSWORD: power_logger_dev_password

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    environment:
      NODE_ENV: development
      DB_NAME: power_logger_dev
      DB_USER: power_logger_dev
      DB_PASSWORD: power_logger_dev_password
      LOG_LEVEL: debug
    volumes:
      - ./backend/src:/app/src
      - ./backend/package.json:/app/package.json
      - ./backend/logs:/app/logs
    ports:
      - "3000:3000"
      - "9229:9229"  # Node.js debugger
    command: npm run dev

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    environment:
      REACT_APP_API_URL: http://localhost:3000/api
      CHOKIDAR_USEPOLLING: true
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
      - ./frontend/package.json:/app/package.json
    ports:
      - "3001:3000"
    command: npm start

  # Remove nginx in development mode
  nginx:
    profiles: ["production"]